/**
 * Master 16-Module Curriculum Engine for AI-ITSM Hub
 * Created for Abhineet Singh | 20+ Years IT Operations Leader
 */

const full16ModuleCurriculum = [
  // LEVEL 1: FOUNDATION (Mods 1-4)
  { chapterNum: 1, level: 1, levelName: "Level 1: Foundation", title: "Service Desk Purpose & Professional Mindset", duration: "45 min", badge: "Helpdesk Basics", desc: "Single Point of Contact (SPOC) role, Helpdesk vs. Service Desk distinction, customer-centric mindset, and ITIL 4 Service Value System foundation.", keyTakeaways: ["SPOC principle eliminates fragmented IT support", "Service Desk focuses on business value and user experience", "Active listening converts technical frustration into trust", "FCR optimization reduces user downtime and cost"] },
  { chapterNum: 2, level: 1, levelName: "Level 1: Foundation", title: "Communication, Empathy & Customer Care", duration: "50 min", badge: "Customer Care", desc: "Active listening techniques, de-escalating anxious users, executive stakeholder communications, and customer satisfaction (CSAT) best practices.", keyTakeaways: ["De-escalation requires acknowledging emotion before root cause", "Jargon-free explanations build user confidence during outages", "Executive summaries require: Impact, Action, Next Update", "CSAT feedback provides actionable coaching insights"] },
  { chapterNum: 3, level: 1, levelName: "Level 1: Foundation", title: "Ticket Lifecycle, Categorisation & Priority", duration: "55 min", badge: "Ticket Lifecycle", desc: "Incident vs Request distinction, Priority Matrix (Impact x Urgency calculation), CTI taxonomy tagging, internal work notes, and resolution tagging.", keyTakeaways: ["Incidents disrupt business; Service Requests ask for access/hardware", "Priority = Impact (users affected) x Urgency (business deadline)", "Accurate CTI tagging enables automated AI ticket triage", "Work notes protect compliance and prevent duplicate troubleshooting"] },
  { chapterNum: 4, level: 1, levelName: "Level 1: Foundation", title: "Foundation Troubleshooting & Security Awareness", duration: "50 min", badge: "Security & Basics", desc: "Structured troubleshooting methodology, verifying caller identity, phishing detection, credential protection, and security incident escalation.", keyTakeaways: ["Structured troubleshooting prevents random guessing and reduces MTTR", "Identity verification via MFA or callback prevents social engineering", "Phishing emails create artificial urgency and domain spoofing", "Suspected breaches require immediate SOC isolation and escalation"] },

  // LEVEL 2: OPERATIONAL PRACTITIONER (Mods 5-8)
  { chapterNum: 5, level: 2, levelName: "Level 2: Operational Practitioner", title: "Identity, Access, Active Directory & Entra ID", duration: "60 min", badge: "Active Directory", desc: "Active Directory Domain Services, Microsoft Entra ID (Azure AD), SSPR, MFA token registration, RBAC permissions, and drive mapping.", keyTakeaways: ["Hybrid identity connects local AD to cloud Microsoft Entra ID", "SSPR and automated MFA resets deflect up to 30% of calls", "Role-Based Access Control (RBAC) enforces least-privilege security", "Shared drive access requires updating AD Security Groups"] },
  { chapterNum: 6, level: 2, levelName: "Level 2: Operational Practitioner", title: "Windows Endpoint, Application & Remote Support", duration: "65 min", badge: "Intune & Endpoints", desc: "MS Intune MDM, Autopilot, Windows Event Viewer, application crash dumps, network printer spoolers, and remote assistance tools.", keyTakeaways: ["Microsoft Intune automates cloud endpoint configuration & security wipes", "Event Viewer Event IDs (e.g. 1000 Error) isolate crash root cause", "Print spooler restarts resolve 80% of stuck printer queues", "Remote support requires user consent before taking screen control"] },
  { chapterNum: 7, level: 2, levelName: "Level 2: Operational Practitioner", title: "Networking, DNS, DHCP, Wi-Fi & VPN Diagnostics", duration: "60 min", badge: "Networking & VPN", desc: "TCP/IP fundamentals, ipconfig, ping, nslookup, traceroute, DHCP lease renewals, Wi-Fi 802.1X enterprise auth, and GlobalProtect VPN.", keyTakeaways: ["Always follow the OSI layer model: Check physical link before software", "DNS failure (nslookup) is the top cause of site load failure", "DHCP lease renewal resets stale IP allocations on corporate Wi-Fi", "VPN timeouts stem from ISP MTU size or MFA expiration"] },
  { chapterNum: 8, level: 2, levelName: "Level 2: Operational Practitioner", title: "Service Requests, Approvals & Vendor Handover", duration: "55 min", badge: "Requests & JML", desc: "Joiners, Movers, Leavers (JML) workflows, hardware provisioning, approval chains, third-party vendor management, and shift handover logs.", keyTakeaways: ["Day 1 Readiness for Joiners requires pre-provisioned hardware & access", "Offboarding (Leavers) requires immediate account lock & data wipe", "Vendor SLAs must match internal Response targets", "Shift handover logs ensure P2 incidents are tracked 24/7"] },

  // LEVEL 3: ADVANCED ANALYST (Mods 9-12)
  { chapterNum: 9, level: 3, levelName: "Level 3: Advanced Analyst", title: "Major Incident Support & Stakeholder Comms", duration: "70 min", badge: "P1 Incidents & CAB", desc: "Declaring P1 Major Incidents, establishing bridge calls, executive communications, Emergency CAB approvals, and Post-Incident Reviews (PIR).", keyTakeaways: ["Major Incident Command separates technical fix from stakeholder comms", "Broadcast status updates must be issued every 30 mins during P1 outages", "Emergency CAB changes require rapid risk evaluation without skipping security", "PIR meetings focus on process improvement, not personal blame"] },
  { chapterNum: 10, level: 3, levelName: "Level 3: Advanced Analyst", title: "Problem Management, Known Errors & 5-Why RCA", duration: "65 min", badge: "Problem Mgt & RCA", desc: "Reactive vs Proactive Problem Management, 5-Why RCA methodology, Fishbone (Ishikawa) diagrams, Known Error Database (KEDB), and workarounds.", keyTakeaways: ["Problem Management eliminates recurring incidents to protect uptime", "5-Why analysis drills down past symptoms to root failure", "KEDB workarounds allow L1 analysts to restore service fast", "Proactive Problem Management fixes flaws before outages occur"] },
  { chapterNum: 11, level: 3, levelName: "Level 3: Advanced Analyst", title: "KCS Methodology, Knowledge Quality & Coaching", duration: "60 min", badge: "KCS & Knowledge", desc: "Knowledge-Centered Service (KCS v6) methodology, Solve Loop (Capture, Structure, Reuse, Improve), Evolve Loop, article quality index (AQI), and coaching.", keyTakeaways: ["KCS integrates knowledge creation directly into ticket resolution", "Capture in the workflow: Write articles while solving tickets", "Reuse & improve: Search first before creating duplicate articles", "AQI audits maintain KB health and prevent outdated guides"] },
  { chapterNum: 12, level: 3, levelName: "Level 3: Advanced Analyst", title: "Automation, Operational Data & Responsible AI", duration: "75 min", badge: "AI & Automation", desc: "Zero-touch ticket triage, LLM intent classification, Retrieval-Augmented Generation (RAG) virtual agents, prompt engineering, and NCSC/OWASP AI safety.", keyTakeaways: ["AI Virtual Agents deflect up to 40% of L1 tickets when grounded in KBs", "RAG architecture prevents AI hallucinations by forcing SOP citations", "Never input real passwords, PII, or patient data into public AI prompts", "Human-in-the-Loop (HITL) validation is mandatory for admin access changes"] },

  // LEVEL 4: LEAD & IMPROVEMENT PRACTITIONER (Mods 13-16)
  { chapterNum: 13, level: 4, levelName: "Level 4: Lead Practitioner", title: "Service Desk Operating Model & Workforce", duration: "80 min", badge: "Leadership & Ops", desc: "Service Desk operating models (Centralized, Distributed, Virtual, Follow-the-Sun), Erlang-C capacity planning, shift roster optimization, and talent retention.", keyTakeaways: ["Operating models (Virtual vs Follow-the-Sun) balance cost and language", "Erlang-C algorithms model call arrival rates to determine staffing", "Under-staffing causes call abandonment and SLA breach", "Clear promotion pathways increase team retention and institutional knowledge"] },
  { chapterNum: 14, level: 4, levelName: "Level 4: Lead Practitioner", title: "Metrics, SLA, XLA & Service-Review Reporting", duration: "75 min", badge: "XLAs & Scorecards", desc: "Transitioning from SLAs to XLAs (Experience Level Agreements), sentiment analysis, executive dashboard design, watermelon index mitigation, and SLA data dictionaries.", keyTakeaways: ["Traditional SLAs measure uptime; XLAs measure end-user productivity", "Watermelon Index indicates operational failure hidden behind green SLAs", "Analyst Scorecards should weigh quality higher than closed ticket count", "Service Reviews focus on business outcomes and continuous value"] },
  { chapterNum: 15, level: 4, levelName: "Level 4: Lead Practitioner", title: "Quality Assurance, Coaching & CSI Register", duration: "70 min", badge: "QA & CSI Register", desc: "Quality Assurance (QA) audit frameworks, 1-on-1 analyst coaching, Continual Improvement Register (CIR), Benchmarking, and Deming Cycle (PDCA).", keyTakeaways: ["QA programs audit call recordings and ticket notes for quality", "Coaching sessions focus on growth rather than punitive measures", "Continual Improvement Register (CIR) tracks all efficiency projects", "PDCA ensures improvements are validated before enterprise rollout"] },
  { chapterNum: 16, level: 4, levelName: "Level 4: Lead Practitioner", title: "AI Governance, Risk Management & Transformation", duration: "90 min", badge: "Capstone & Governance", desc: "AI risk registers, ISO 42001 AI Management System, ROI calculation for ITSM tooling, and the Grand Master 90-Day Service Desk Transformation Capstone.", keyTakeaways: ["AI Governance mandates logging prompt data, securing APIs, and auditing drift", "Tooling migrations require calculating Total Cost of Ownership (TCO)", "A 90-day roadmap balances quick wins with strategic KCS/XLA changes", "Grand Master Capstone validates end-to-end operational mastery"] }
];

// Globally expose full 16-module curriculum for index.html rendering
window.platformCourseChapters = full16ModuleCurriculum;
